excluded: 
  - Carthage
  - Pods
#disabled_rules:
  #- shorthand_operator
  #- trailing_whitespace
trailing_whitespace:
  ignores_empty_lines: true
force_cast: warning
force_try: warning
line_length: 200
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone
identifier_name:
  min_length: # only min_length
    warning: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - uid
    - UID
    - Id
    - ID
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
